INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (1, N'Vacances', 1, N'V', 1)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (2, N'Formations', 1, N'F', 2)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (3, N'Congé', 1, N'C', 3)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (4, N'Tâches administratives', 1, N'T', 4)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (5, N'Helpdesk', 1, N'H', 5)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (6, N'Autre', 1, N'A', 9)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (7, N'Maintenance Infrastructure', 1, N'M', 6)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (8, N'EDM/IDEX', 1, N'E', 10)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (9, N'Maladie / accident', 1, N'L', 11)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (10, N'Maintenance SAP', 1, N'S', 7)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (11, N'SAP Allgemein', 1, N'P', 8)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (12, N'Planification de projets', 1, N'P', 12)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (13, N'CISO', 1, N'I', 13)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (14, N'Tarifs G/W/E', 1, NULL, 14)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (15, N'IT-Board', 1, NULL, 15)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (16, N'Séance cadres', 1, NULL, 16)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (17, N'Jahresabschluss', 1, NULL, 17)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (18, N'Know-How Transfer', 1, NULL, 18)
INSERT INTO [dbo].[AdminResources] ([ID_AdminResource], [AdminResource], [Enable], [Symbol], [DisplayOrder]) VALUES (19, N'Documentation', 1, NULL, 19)
