INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (1, N'Général', 1, 1)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (2, N'Application', 1, 2)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (3, N'Administratif', 1, 3)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (4, N'Infrastructure client', 1, 4)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (5, N'Infrastructure serveur', 1, 5)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (6, N'Infrastructure réseau', 1, 6)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (7, N'Infrastructure client / serveur', 1, 7)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (8, N'Infrastructure réseau / serveur', 1, 8)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (9, N'Infrastructure réseau / application', 1, 9)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (10, N'Infrastructure serveur / SAP', 1, 10)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (11, N'Téléphonie fixe', 1, 11)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (12, N'Téléphone mobile', 1, 12)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (13, N'SAP général', 1, 13)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (14, N'SAP interface (SAP<>Tiers)', 1, 14)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (15, N'SAP FI/CO (comptabilité)', 1, 15)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (16, N'SAP SD/PM/PS (exploitation/vente/projet)', 1, 16)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (17, N'SAP MM/LO (Logistique)', 1, 17)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (18, N'SAP ISU (gestion énergie)', 1, 18)
INSERT INTO [dbo].[ProjectCategories] ([ID_Category], [Category], [Enable], [DisplayOrder]) VALUES (19, N'SAP EDM/IDEX (marché libre)', 1, 19)
